package it.polimi.ingsw.am48.model.factory;

import java.util.List;

/**
 * Defines the contract for factories responsible for generating board game components.
 * <p>
 * This generic interface ensures a standardized approach for instantiating collections
 * of game items (such as cards or track cards) whose composition or quantity strictly
 * depends on the number of players participating in the match.
 *
 * @param <T> the specific type of component generated by this factory
 */
public interface BoardFactory<T> {

    /**
     * Generates a list of game components tailored for the specified number of players.
     *
     * @param numPlayers the number of players in the current game
     * @return a fully initialized list of components of type {@code T}
     */
    List<T> createCards(int numPlayers);
}