package it.polimi.ingsw.am48.model.factory;

import it.polimi.ingsw.am48.dto.CardDTO;
import it.polimi.ingsw.am48.dto.StrategyDTO;
import it.polimi.ingsw.am48.model.card.BuildingCard;
import it.polimi.ingsw.am48.model.enums.CharacterType;
import it.polimi.ingsw.am48.model.enums.Era;
import it.polimi.ingsw.am48.model.enums.EventType;
import it.polimi.ingsw.am48.model.enums.Resource;
import it.polimi.ingsw.am48.model.strategy.*;

import java.util.ArrayList;
import java.util.List;

/**
 * A concrete factory responsible for instantiating {@link BuildingCard} objects.
 * <p>
 * This factory parses a list of data transfer objects (DTOs) to generate the game's building deck.
 * Building cards possess complex strategies that can trigger during various, distinct phases
 * of the game. Therefore, this factory is responsible for dynamically composing both the
 * specific effect (the strategy) and its corresponding trigger timing (the registration action).
 * This approach ensures complete modularity and separation of concerns
 */
public class BuildingFactory implements BoardFactory<BuildingCard> {
    private final List<CardDTO> buildings;

    /**
     * Creates a new {@code BuildingFactory} initialized with the base building data.
     *
     * @param buildings a list of {@link CardDTO} containing the blueprints for all available building cards
     */
    public BuildingFactory(List<CardDTO> buildings) {
        this.buildings = buildings;
    }

    /**
     * Generates the complete deck of building cards for the game.
     *
     * @param numPlayers the number of players in the game (must be between 2 and 5)
     * @return a fully initialized list of {@link BuildingCard} ready to be selected by the board
     * @throws IllegalArgumentException if the number of players is outside the valid range (2-5)
     */
    @Override
    public List<BuildingCard> createCards(int numPlayers) {
        if(numPlayers < 2 || numPlayers > 5) throw new IllegalArgumentException("Invalid number of players");
        List<BuildingCard> buildingDeck = new ArrayList<>();

        for (CardDTO dto : this.buildings) {
            Era era =  Era.valueOf(dto.era);

            CardStrategy strategy = null;
            if(dto.strategy != null){
                strategy = buildStrategy(dto.strategy);
            }

            buildingDeck.add(new BuildingCard(dto.id, era, strategy, dto.foodCost, dto.prestigePoints));
        }

        return  buildingDeck;
    }

    /**
     * Constructs the active strategy for a building card and binds it to its specific trigger event.
     * <p>
     * This method dynamically links the specific effect logic with the appropriate
     * registration hook generated by {@link #buildRegistrationAction(StrategyDTO)}.
     *
     * @param dto the strategy blueprint containing the specific effect type and required parameters
     * @return the instantiated {@link CardStrategy} bound to its appropriate lifecycle trigger
     * @throws IllegalArgumentException if the strategy specified in the DTO is unknown
     */
    private CardStrategy buildStrategy(StrategyDTO dto) {
        switch (dto.effect){
            case "ExtraFoodOnFoodStrategy": return new ExtraFoodOnFoodStrategy(buildRegistrationAction(dto));
            case "InventorsPairStrategy": return new InventorsPairStrategy(buildRegistrationAction(dto));
            case "ShamanSafetyStrategy": return new ShamanSafetyStrategy(buildRegistrationAction(dto));
            case "AllSetFoodStrategy": return new AllSetFoodStrategy(buildRegistrationAction(dto));
            case "HuntEventStrategy": return new HuntEventStrategy(dto.num1, buildRegistrationAction(dto));
            case "DoubleBuilderPPStrategy": return new DoubleBuilderPPStrategy(buildRegistrationAction(dto));
            case "DoubleShamanPPStrategy": return new DoubleShamanPPStrategy(buildRegistrationAction(dto));
            case "ExtraPickStrategy": return new ExtraPickStrategy(buildRegistrationAction(dto));
            case "ResourcePerCharStrategy": {
                Resource resource = Resource.valueOf(dto.resource);
                CharacterType type = CharacterType.valueOf(dto.character);
                return new ResourcePerCharStrategy(resource, dto.num1, type, buildRegistrationAction(dto));
            }
            case "UpdateResourcesStrategy":  {
                Resource resource = Resource.valueOf(dto.resource);
                return new UpdateResourcesStrategy(resource, dto.num1, buildRegistrationAction(dto));
            }
            default: throw new IllegalArgumentException("Invalid building strategy");
        }
    }

    /**
     * Determines the correct notification channel and constructs the registration hook
     * for a building's strategy.
     * <p>
     * Building effects can activate at different moments (e.g., when a totem is returned,
     * upon picking a card, during events, at the end of the offer phase or at the end of the game).
     * This method parses the requested trigger timing from the DTO and routes the registration
     * to the corresponding specialized notificator inside the {@code NotificatorCenter}.
     *
     * @param dto the strategy blueprint specifying the required trigger timing
     * @return a {@link RegistrationAction} lambda function that attaches the strategy to the correct observer channel
     * @throws IllegalArgumentException if the specified notificator channel is unknown
     */
    private RegistrationAction buildRegistrationAction(StrategyDTO dto) {
        switch (dto.notificator) {
            case "OnTotemReturned": return (nc, pc, s) -> {nc.getTotemReturnedNotificator().attach(pc.getCurrPlayer(), s);};
            case "OnPick": return (nc, pc, s) -> {nc.getPickNotificator().attach(pc.getCurrPlayer(), s);};
            case "OnEvent": return (nc, pc, s) -> {nc.getEventNotificator().attach(EventType.valueOf(dto.eventType), pc.getCurrPlayer(), s);};
            case "OnEndOfferPhase": return (nc, pc, s) -> {nc.getEndOfferPhaseNotificator().attach(pc.getCurrPlayer(), s);};
            case "OnEndGame": return (nc, pc, s) -> {nc.getEndGameNotificator().attach(pc.getCurrPlayer(), s);};
            default: throw new IllegalArgumentException("Invalid building notificator");
        }
    }
}
