package it.polimi.ingsw.am48.model.factory;

import it.polimi.ingsw.am48.model.card.BuildingCard;
import it.polimi.ingsw.am48.model.card.Card;
import it.polimi.ingsw.am48.model.card.CharacterCard;
import it.polimi.ingsw.am48.model.card.EventCard;
import it.polimi.ingsw.am48.model.enums.Era;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.Map;

/**
 * Responsible for assembling, shuffling, and ordering the final playable decks.
 * <p>
 * This class takes the raw collections of cards generated by the factories and
 * applies the specific game rules to build the Tribe Deck and the Building Deck.
 * It handles the complex logic of era-based sorting, randomizing subsets, and
 * placing specific cards at the top or bottom of the decks.
 */
public class DeckSetup {
    private final List<CharacterCard> characters;
    private final List<EventCard> events;
    private final List<BuildingCard> buildings;
    private final Map<Integer, Map<Era, Integer>> buildingSetup;

    /**
     * Creates a new {@code DeckSetup} instance with the raw game components.
     * <p>
     * Defensive copies of the provided card lists are created internally, ensuring
     * that the destructive operations (like removals and sub-listing) performed
     * during deck creation do not affect the original factory outputs.
     *
     * @param characters    the complete list of available character cards
     * @param events        the complete list of available event cards
     * @param buildings     the complete list of available building cards
     * @param buildingSetup a configuration map defining the exact amount of building
     *                      cards to draw per era, based on the number of players
     */
    public DeckSetup(List<CharacterCard> characters, List<EventCard> events, List<BuildingCard> buildings,
                      Map<Integer, Map<Era, Integer>> buildingSetup) {
        this.characters = new ArrayList<>(characters);
        this.events = new ArrayList<>(events);
        this.buildings = new ArrayList<>(buildings);
        this.buildingSetup = buildingSetup;
    }

    /**
     * Assembles the Tribe Deck according to the game's specific structural rules.
     * <p>
     * The resulting deck is structured from top to bottom as follows:
     * <ul>
     * <li><b>Top:</b> A specific number ({@code numPlayers + 1}) of randomized character cards of Era I.
     *                 This ensures the absence of events in the lower row for the initial game setup. </li>
     * <li><b>Middle:</b> The remaining character cards mixed with the event cards, shuffled and then
     *                    strictly sorted by Era.</li>
     * <li><b>Bottom:</b> The two final event cards. <i>Note: This method assumes the final events are permanently
     *                    located at the very end of the provided events list (enforced by the JSON structure).</i></li>
     * </ul>
     *
     * @param numPlayers the number of players in the game (must be between 2 and 5)
     * @return the fully structured and ordered Tribe Deck ready for gameplay
     * @throws IllegalArgumentException if the number of players is outside the valid range (2-5)
     */
    public List<Card> createTribeDeck(int numPlayers){
        if(numPlayers < 2 || numPlayers > 5) throw new IllegalArgumentException("Invalid number of players");

        // Shuffle characters
        Collections.shuffle(characters);

        // Order per Era and set first numPlayers + 1 cards on top of the tribe deck (for lowerRow)
        List<CharacterCard> onTopCards = new ArrayList<>( this.characters.stream()
                .sorted((c1, c2) -> Integer.compare(c1.getEra().getIndex(), c2.getEra().getIndex()))
                .limit(numPlayers + 1)
                .toList());

        this.characters.removeAll(onTopCards);
        List<Card> tribeDeck = new ArrayList<>(onTopCards);

        // Extract final events (last two in event list, guaranteed by json file)
        List<Card> finalEvents = new ArrayList<>(this.events.subList(this.events.size() - 2, this.events.size()));
        this.events.subList(this.events.size() - 2, this.events.size()).clear();

        // Mix characters and events
        List<Card> mixTribe = new ArrayList<>(this.characters);
        mixTribe.addAll(this.events);
        Collections.shuffle(mixTribe);

        // Order per Era and add to tribe deck
        tribeDeck.addAll(mixTribe.stream()
                .sorted((c1, c2) -> Integer.compare(c1.getEra().getIndex(), c2.getEra().getIndex()))
                .toList());

        // Add final events to the bottom
        tribeDeck.addAll(finalEvents);

        return tribeDeck;
    }

    /**
     * Assembles the Building Deck according to the game's era-based configuration.
     * <p>
     * The method shuffles the entire pool of building cards and then iteratively
     * extracts a precise number of cards for each era, as dictated by the
     * {@code buildingSetup} map for the given player count. The final deck is ordered
     * chronologically by Era.
     *
     * @param numPlayers the number of players in the game (must be between 2 and 5)
     * @return the fully structured Building Deck ready for gameplay
     * @throws IllegalArgumentException if the number of players is outside the valid range (2-5)
     */
    public List<BuildingCard> createBuildingDeck(int numPlayers){
        if(numPlayers < 2 || numPlayers > 5) throw new IllegalArgumentException("Invalid number of players");
        Collections.shuffle(buildings);
        List<BuildingCard> buildingDeck = new ArrayList<>();

        for(Era era : Era.values()){
            buildingDeck.addAll(this.buildings.stream()
                    .filter(b -> b.getEra().equals(era))
                    .limit(this.buildingSetup.get(numPlayers).get(era))
                    .toList());
        }
        return buildingDeck;
    }
}
