package it.polimi.ingsw.am48.model.phase;

import it.polimi.ingsw.am48.exception.InvalidActionException;
import it.polimi.ingsw.am48.model.delta.GameDelta;
import it.polimi.ingsw.am48.model.game.Game;
import it.polimi.ingsw.am48.model.player.Player;
import it.polimi.ingsw.am48.model.player.PlayerContext;
import it.polimi.ingsw.am48.model.snapshot.PhaseSnapshot;
import it.polimi.ingsw.am48.model.snapshot.PlaceTotemPhaseSnapshot;
import it.polimi.ingsw.am48.model.snapshot.PlayerOfferPhaseSnapshot;

import java.util.List;
import java.util.Set;
import java.util.stream.Collectors;

/**
 * Defines the contract for the State pattern managing the game's lifecycle.
 * <p>
 * This interface represents a discrete phase (state) of the game. It declares all
 * possible player actions as default methods that automatically throw an
 * {@link InvalidActionException}. Concrete phase implementations will override
 * only the specific actions that are legally allowed during that particular state,
 * enforcing the game rules dynamically and avoiding massive conditional blocks
 * in the main Game class.
 */
public interface GamePhase {

    /**
     * Handles a player's request to join the game lobby.
     *
     * @param playerContext           the context holding players data
     * @param game                    the main game instance
     * @param playerNickname          the nickname of the joining player
     * @throws InvalidActionException if joining is not allowed in the current phase (default behavior)
     */
    default void addPlayer(PlayerContext playerContext,Game game, String playerNickname){
        throw new InvalidActionException("Cannot compute the action in this phase");
    }

    /**
     * Handles a player's request to place their totem on the offer track.
     *
     * @param game                    the main game instance
     * @param player                  the player attempting the action
     * @param position                the character identifier of the chosen track slot
     * @return                        a list of state changes (deltas) generated by the action
     * @throws InvalidActionException if placing a totem is not allowed in the current phase (default behavior)
     */
    default List<GameDelta> placeTotem(Game game, Player player, char position){
        throw new InvalidActionException("Cannot compute the action in this phase");
    }

    /**
     * Handles a player's request to acquire a specific card from the board.
     *
     * @param game                    the main game instance
     * @param player                  the player attempting the action
     * @param cardId                  the unique identifier of the target card
     * @return                        a list of state changes (deltas) generated by the action
     * @throws InvalidActionException if taking a card is not allowed in the current phase (default behavior)
     */
    default List<GameDelta> takeCard(Game game, Player player, String cardId){
        throw new InvalidActionException("Cannot compute the action in this phase");
    }

    /**
     * Serializes the current phase into a data transfer object for network or storage.
     *
     * @return the snapshot representing the current phase and its internal state
     */
    PhaseSnapshot toSnapshot();

    /**
     * Reconstructs the exact game phase from a previously saved snapshot.
     * <p>
     * This static factory method acts as the state deserializer. It identifies the
     * correct concrete phase type from the snapshot's name and properly relinks
     * any required {@link Player} instances using their nicknames.
     * <p>
     * Note: Transient phases like {@code END_TURN} or {@code END_GAME} cannot be
     * directly restored from a snapshot, as they are immediate resolution states.
     *
     * @param snapshot   the serialized phase state
     * @param players    the list of currently active players in the game to be relinked
     * @param numPlayers the total number of players configured for the game
     * @return the fully reconstructed concrete {@link GamePhase}
     * @throws IllegalStateException if the phase is transient or unknown
     */
    public static GamePhase fromSnapshot(PhaseSnapshot snapshot, List<Player> players, int numPlayers) {
        switch (snapshot.getPhaseName()) {
            case "WAITING_FOR_PLAYERS":
                return new WaitingForPlayersPhase(numPlayers);

            case "PLACE_TOTEM": {
                PlaceTotemPhaseSnapshot s = (PlaceTotemPhaseSnapshot) snapshot;
                Set<Player> placed = players.stream()
                        .filter(p -> s.getPlayersPlacedNicknames().contains(p.getNickname()))
                        .collect(Collectors.toSet());
                return new PlaceTotemPhase(placed);
            }

            case "PLAYER_OFFER": {
                PlayerOfferPhaseSnapshot s = (PlayerOfferPhaseSnapshot) snapshot;
                List<Player> actionOrder = s.getActionOrderNicknames().stream()
                        .map(nick -> players.stream()
                                .filter(p -> p.getNickname().equals(nick))
                                .findFirst().orElseThrow())
                        .collect(Collectors.toList());

                Player extraPickPlayer = s.getExtraPickPlayerNickname() != null
                        ? players.stream()
                        .filter(p -> p.getNickname().equals(s.getExtraPickPlayerNickname()))
                        .findFirst().orElseThrow()
                        : null;

                return new PlayerOfferPhase(actionOrder, s.getCurrIdx(), s.getPicksFromUp(),
                        s.getPicksFromDown(), s.getExtraPickActive(),
                        extraPickPlayer, s.getTotemReturned());
            }

            case "END_TURN":
            case "END_GAME":
                throw new IllegalStateException("Unrestorable phase: " + snapshot.getPhaseName());

            default:
                throw new IllegalStateException("Unrestorable phase: " + snapshot.getPhaseName());
        }
    }
}
